ALTER TABLE ADMINISTRACION.TIPO_MONEDA
 DROP PRIMARY KEY CASCADE;

DROP TABLE ADMINISTRACION.TIPO_MONEDA CASCADE CONSTRAINTS;

CREATE TABLE ADMINISTRACION.TIPO_MONEDA
(
  ID      NUMBER(18)                            NOT NULL,
  TIPO    VARCHAR2(5 BYTE)                      NOT NULL,
  NOMBRE  VARCHAR2(18 BYTE)                     NOT NULL,
  ESTADO  CHAR(1 BYTE)                          DEFAULT 'A'                   NOT NULL
)
TABLESPACE ADMINISTRACION
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX ADMINISTRACION.IDX_TIPO_MONEDA_ID ON ADMINISTRACION.TIPO_MONEDA
(ID)
LOGGING
TABLESPACE ADMINISTRACION
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER ADMINISTRACION.TIPO_MONEDA_TRG
BEFORE INSERT
ON ADMINISTRACION.TIPO_MONEDA
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DISABLE
BEGIN
-- For Toad:  Highlight column ID
  :new.ID := TIPO_MONEDA_SEQ.nextval;
END TIPO_MONEDA_TRG;
/


DROP PUBLIC SYNONYM TIPO_MONEDA;

CREATE OR REPLACE PUBLIC SYNONYM TIPO_MONEDA FOR ADMINISTRACION.TIPO_MONEDA;


ALTER TABLE ADMINISTRACION.TIPO_MONEDA ADD (
  CONSTRAINT PK_TIPO_MONEDA_ID
  PRIMARY KEY
  (ID)
  USING INDEX ADMINISTRACION.IDX_TIPO_MONEDA_ID
  ENABLE VALIDATE);

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON ADMINISTRACION.TIPO_MONEDA TO PUBLIC;

Insert into ADMINISTRACION.TIPO_MONEDA
   (ID, TIPO, NOMBRE, ESTADO)
 Values
   (1, 'peso', 'PESOS', 'A');
Insert into ADMINISTRACION.TIPO_MONEDA
   (ID, TIPO, NOMBRE, ESTADO)
 Values
   (2, 'dolar', 'DÓLAR', 'A');
Insert into ADMINISTRACION.TIPO_MONEDA
   (ID, TIPO, NOMBRE, ESTADO)
 Values
   (3, 'euro', 'EURO', 'A');
COMMIT;
