ALTER TABLE ADMINISTRACION.CLIENTES
 DROP PRIMARY KEY CASCADE;

DROP TABLE ADMINISTRACION.CLIENTES CASCADE CONSTRAINTS;

CREATE TABLE ADMINISTRACION.CLIENTES
(
  ID                 NUMBER(18)                 NOT NULL,
  NOMBRE             VARCHAR2(80 BYTE)          NOT NULL,
  APELLIDO           VARCHAR2(250 BYTE)         NOT NULL,
  TIPO_DOCUMENTO_ID  NUMBER(18)                 NOT NULL,
  TIPO_CLIENTE       CHAR(1 BYTE)               NOT NULL,
  NUMERO_DOCUMENTO   NUMBER(18)                 NOT NULL,
  RUT                NUMBER(18)                 NOT NULL,
  RAZON_SOCIAL       VARCHAR2(100 BYTE),
  ANO_FUNDACION      VARCHAR2(4 BYTE)
)
TABLESPACE ADMINISTRACION
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX ADMINISTRACION.IDX_NUMERO_DOCUMENTOS ON ADMINISTRACION.CLIENTES
(NUMERO_DOCUMENTO)
LOGGING
TABLESPACE ADMINISTRACION
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX ADMINISTRACION.IXD_ID_CLIENTES ON ADMINISTRACION.CLIENTES
(ID)
LOGGING
TABLESPACE ADMINISTRACION
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX ADMINISTRACION.UK_RUT_CLIENTES ON ADMINISTRACION.CLIENTES
(RUT)
LOGGING
TABLESPACE ADMINISTRACION
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER ADMINISTRACION.CLIENTES_TRG
BEFORE INSERT
ON ADMINISTRACION.Clientes
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DISABLE
BEGIN
-- For Toad:  Highlight column ID
  :new.ID := Clientes2_SEQ.nextval;
END Clientes_TRG;
/


DROP PUBLIC SYNONYM CLIENTES;

CREATE OR REPLACE PUBLIC SYNONYM CLIENTES FOR ADMINISTRACION.CLIENTES;


ALTER TABLE ADMINISTRACION.CLIENTES ADD (
  CONSTRAINT PK_CLIENTES
  PRIMARY KEY
  (ID)
  USING INDEX ADMINISTRACION.IXD_ID_CLIENTES
  ENABLE VALIDATE,
  CONSTRAINT UK_CLIENTES_RUT
  UNIQUE (RUT)
  USING INDEX ADMINISTRACION.UK_RUT_CLIENTES
  ENABLE VALIDATE);

ALTER TABLE ADMINISTRACION.CLIENTES ADD (
  CONSTRAINT FK_CLIENTES_TIPO_DOCUMENTO_ID 
  FOREIGN KEY (TIPO_DOCUMENTO_ID) 
  REFERENCES ADMINISTRACION.TIPO_DOCUMENTO (ID)
  ENABLE VALIDATE);

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON ADMINISTRACION.CLIENTES TO PUBLIC;

Insert into ADMINISTRACION.CLIENTES
   (ID, NOMBRE, APELLIDO, TIPO_DOCUMENTO_ID, TIPO_CLIENTE, 
    NUMERO_DOCUMENTO, RUT, RAZON_SOCIAL, ANO_FUNDACION)
 Values
   (1, 'prueba', '1', 1, 'N', 
    1111, 1, NULL, NULL);
Insert into ADMINISTRACION.CLIENTES
   (ID, NOMBRE, APELLIDO, TIPO_DOCUMENTO_ID, TIPO_CLIENTE, 
    NUMERO_DOCUMENTO, RUT, RAZON_SOCIAL, ANO_FUNDACION)
 Values
   (2, 'prueba', '1', 1, 'J', 
    2222, 2, 'prueba', '2021');
COMMIT;
