ALTER TABLE ADMINISTRACION.CUENTAS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ADMINISTRACION.CUENTAS CASCADE CONSTRAINTS;

CREATE TABLE ADMINISTRACION.CUENTAS
(
  ID              NUMBER(18)                    NOT NULL,
  CLIENTE_ID      NUMBER(18)                    NOT NULL,
  NUMERO_CUENTA   NUMBER(25)                    NOT NULL,
  TIPO_MONEDA_ID  NUMBER(18),
  SALDO           NUMBER(35,2),
  ESTADO          CHAR(1 BYTE)
)
TABLESPACE ADMINISTRACION
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX ADMINISTRACION.IDX_CUENTA_ID ON ADMINISTRACION.CUENTAS
(ID)
LOGGING
TABLESPACE ADMINISTRACION
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX ADMINISTRACION.UK_CNUMERO_CUENTA ON ADMINISTRACION.CUENTAS
(NUMERO_CUENTA)
LOGGING
TABLESPACE ADMINISTRACION
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER ADMINISTRACION.CUENTAS_TRG
BEFORE INSERT
ON ADMINISTRACION.CUENTAS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DISABLE
BEGIN
-- For Toad:  Highlight column ID
  :new.ID := CUENTAS_SEQ.nextval;
END CUENTAS_TRG;
/


DROP PUBLIC SYNONYM CUENTAS;

CREATE OR REPLACE PUBLIC SYNONYM CUENTAS FOR ADMINISTRACION.CUENTAS;


ALTER TABLE ADMINISTRACION.CUENTAS ADD (
  CONSTRAINT PK_CUENTA_ID
  PRIMARY KEY
  (ID)
  USING INDEX ADMINISTRACION.IDX_CUENTA_ID
  ENABLE VALIDATE,
  CONSTRAINT UK_NUMERO_CUENTA
  UNIQUE (NUMERO_CUENTA)
  USING INDEX ADMINISTRACION.UK_CNUMERO_CUENTA
  ENABLE VALIDATE);

ALTER TABLE ADMINISTRACION.CUENTAS ADD (
  CONSTRAINT FK_CLIENTES_ID 
  FOREIGN KEY (CLIENTE_ID) 
  REFERENCES ADMINISTRACION.CLIENTES (ID)
  ENABLE VALIDATE,
  CONSTRAINT FK_TIPO_MONEDA_ID 
  FOREIGN KEY (TIPO_MONEDA_ID) 
  REFERENCES ADMINISTRACION.TIPO_MONEDA (ID)
  ENABLE VALIDATE);

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON ADMINISTRACION.CUENTAS TO PUBLIC;

Insert into ADMINISTRACION.CUENTAS
   (ID, CLIENTE_ID, NUMERO_CUENTA, TIPO_MONEDA_ID, SALDO, 
    ESTADO)
 Values
   (1, 1, 1111, 1, 1000, 
    'A');
COMMIT;
