ALTER TABLE ADMINISTRACION.MOVIMIENTOS
 DROP PRIMARY KEY CASCADE;

DROP TABLE ADMINISTRACION.MOVIMIENTOS CASCADE CONSTRAINTS;

CREATE TABLE ADMINISTRACION.MOVIMIENTOS
(
  ID         NUMBER(18)                         NOT NULL,
  CUENTA_ID  NUMBER(18)                         NOT NULL,
  SIGNO      CHAR(1 BYTE)                       NOT NULL,
  VALOR      NUMBER(18,2)                       NOT NULL,
  SALDO      NUMBER(35,2)
)
TABLESPACE ADMINISTRACION
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX ADMINISTRACION.IDX_MOVIMIENTO_ID ON ADMINISTRACION.MOVIMIENTOS
(ID)
LOGGING
TABLESPACE ADMINISTRACION
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER ADMINISTRACION.MOVIMIENTOS_TRG
BEFORE INSERT
ON ADMINISTRACION.MOVIMIENTOS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DISABLE
BEGIN
-- For Toad:  Highlight column ID
  :new.ID := MOVIMIENTOS_SEQ.nextval;
END MOVIMIENTOS_TRG;
/


CREATE OR REPLACE TRIGGER ADMINISTRACION."update_saldo" before
insert or update ON "ADMINISTRACION"."MOVIMIENTOS" FOR EACH ROW
declare
ls_signo char;

BEGIN

ls_signo := :new.signo;
if inserting then 
:new.saldo :=   :new.valor;
else 
if ls_signo = '+' then 
:new.saldo := :old.saldo + :new.valor;
else
:new.saldo := :old.saldo - :new.valor;
end if;  
end if; 
END;
/


DROP PUBLIC SYNONYM MOVIMIENTOS;

CREATE OR REPLACE PUBLIC SYNONYM MOVIMIENTOS FOR ADMINISTRACION.MOVIMIENTOS;


ALTER TABLE ADMINISTRACION.MOVIMIENTOS ADD (
  CONSTRAINT PK_MOVIMIENTO_ID
  PRIMARY KEY
  (ID)
  USING INDEX ADMINISTRACION.IDX_MOVIMIENTO_ID
  ENABLE VALIDATE);

ALTER TABLE ADMINISTRACION.MOVIMIENTOS ADD (
  CONSTRAINT FK_CUENTA_ID_MOV 
  FOREIGN KEY (CUENTA_ID) 
  REFERENCES ADMINISTRACION.CUENTAS (ID)
  ENABLE VALIDATE);

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON ADMINISTRACION.MOVIMIENTOS TO PUBLIC;

Insert into ADMINISTRACION.MOVIMIENTOS
   (ID, CUENTA_ID, SIGNO, VALOR, SALDO)
 Values
   (3, 1, '+', 100000, 100000);
Insert into ADMINISTRACION.MOVIMIENTOS
   (ID, CUENTA_ID, SIGNO, VALOR, SALDO)
 Values
   (1, 1, '+', 100000, 100000);
Insert into ADMINISTRACION.MOVIMIENTOS
   (ID, CUENTA_ID, SIGNO, VALOR, SALDO)
 Values
   (2, 1, '+', 100000, 100000);
COMMIT;
